### PR TITLE
handle slack error 429

### PR DESCRIPTION
**Pull request by fberrez**
## Description

This modifies the behavior when an error `429 - Too Many Requests` occur when it sends a request to slack. It now prints a log instead of raising an error.

Before that, the log that occured the failure was pushed in a "pending" queue. This queue doesn't wait long enough to send another request to slack, resulting in another `429`.

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Execution of test code is failing.

**Comment by nsano-rururu** [comment]
@fberrez 
Please correct the test code so that it does not cause an error.

**Comment by JeffAshton** [comment]
Doesn't this now result in the alert getting lost?  Like how does Elastalert know how to retry later?

**Comment by nsano-rururu** [comment]
@jertel 

I think this pull request with no response should be closed.

**Pull request closed without merging**
