### PR TITLE
Implements ms_teams params as configurable env variables

### PR DESCRIPTION
**Pull request by dNvl**
Hello jertel and community,

first i want to thank you for the great work with elastalert2. We are using it at work and are so happy to have it. I wanted to give something back.

We had the requirement not to add credentials (like usernames, password, but also webhook urls) into the repository of the rules. We are handling credentials in kubernetes secrets all the way. So i created this pull request. And this is what it does.

- Remove the requirement for the ms_teams_webhook_url setting in the Microsoft Teams alert - basically transforming this to an optional setting. Still works if set though.
- Instead enables the user to define an environment variable that contains the value for the setting

The process works like this
1. The user can define a new prefix variable in the alerter settings like this: ms_teams_env_prefix: "MY_PREFIX"
2. Then the user will create an environment var using the prefix and the fixed identifier for the settings like this: MY_PREFIX_MS_TEAMS_WEBHOOK_URL="https://webhookurlhere"
3. This will enable the user to create various env variables for various teams alerters by just changing the prefix or even using the same prefix if the webhook url is used more than once
3. Then just use the alerter as normal

1. This also works for the proxy setting, too. You can set it via env variable but this is optional, too. It also uses the prefix.

- Documentation is updated and included
- Tests are updated and included for the new additions

Please let me know if i could do something better or something is not correctly done. I am not that fluent in python :)

Best regards, keep up the good work

### CODE REVIEW

**Comment by jertel** [comment]
This PR appears to include two concepts:
1. Introduction of an environment prefix, so that rules can pull secrets from a pool of secrets tied to an environment.
2. The ability to pull environment variables from the OS during rule initialization.

The first concept is interesting and I can see the usefulness but I believe something like this would be best applied across all rule and alert settings, rather than only being supported for a single alerter, in this case MS Teams.

The second concept seems to be replicating YAML parsing functionality that can already substitute environment variables during the rule parse phase, rather than during the (later) rule initialization phase. Please take a look at this PR which was accepted into the project several weeks ago: https://github.com/jertel/elastalert2/pull/149. 

Given that #2 can be accomplished today with `$FOO` values inside of rule yaml, I'm not sure that there is much value then to adding #1. When I hear "environment" I think of DEV, PRE-PRODUCTION, and PRODUCTION. In that type of environment structure there would not be a need to include an environment prefix, because each environment would only ever have a single set of secrets defined. Perhaps you could give an example of how you're using environments to better illustrate the benefit.

**Comment by nsano-rururu** [comment]
I forgot to delete the code that I think I added to teams.py for confirmation during development.

teams.py L28
 print(webhookUrl)

teams.py L31
 print(self.ms_teams_webhook_url)

**Comment by dNvl** [comment]
Hey @jertel 
thank you very much for your time! :)

I will have a look at your advice in a few days - currently in release stress. 

Regarding the environment variable question:

We are deploying on k8s so indeed we have different cluster nodes etc. for each deployment environment (staging, production ...)

What I wanted to accomplish with this is, we are using various rules with teams webhook alerts per deployed environment - so we need various environment variables with different webhook urls for different teams channels. That's what the prefix is for. To distinguish between the different specified alerts because the name of the  MS_TEAMS_WEBHOOK_URL env variable is the same for each rule without a specifix prefix. So like this we could define one prefix per teams alert definition and one teams webhook url per alert definition in the same environment.

But i think your proposal is better anyway so i will have a look again in a few days.

**Comment by jertel** [comment]
Closing this PR due to staleness. I suspect @dNvl chose to utilize the proposed solution in https://github.com/jertel/elastalert2/pull/290#issuecomment-868774372.

**Pull request closed without merging**
