### PR TITLE
#156 Support multiple directories in FileRulesLoader

### PR DESCRIPTION
**Pull request by mrfroggg**
Fix: https://github.com/jertel/elastalert2/issues/156 & Openshift/Kubernetes directory issue from https://github.com/Yelp/elastalert/issues/3111

### CODE REVIEW

**Review by jertel — DISMISSED** [review]
Thanks!

**Comment by jertel** [comment]
Can you update the changelog.md file with this feature?

**Comment by mrfroggg** [comment]
Sure!

**Comment by mrfroggg** [comment]
Done

**Review by jertel — APPROVED** [review]

**Pull request merged**
