### PR TITLE
helm add email config

### PR DESCRIPTION
**Pull request by lusson-luo**
## Description

helm provides email smtp-secret，easy help people use email notification
Only helm configuration changes are included

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by jertel** [comment]
What's the benefit of using this vs the suggested method of an extra volume mount (commented out at the bottom of values.yaml)? While this would work it means storing credentials in the values.yaml, vs the suggested method of creating the credentials as a secret separately from the chart's general config.

If we proceed with this PR then the documentation needs to be updated in README.md, and an explanation should be included that notes the difference between using this method vs the other method. Also the contributing guidelines must be reviewed and the changelog needs to be updated.

**Comment by lusson-luo** [comment]
It is the practice of the multi-volume mount method. Before smtp-auth Secret was created manually. 
This commit is a configuration that automatically creates a secret based on the values configuration and uses it with mount.
After this pr, users use email alerts instead of manually creating secrets themselves, just release the annotations

**Comment by lusson-luo** [comment]
> proceed with
Do you think this pr will continue?

**Comment by lusson-luo** [comment]
Do you think this pr will continue?

**Comment by jertel** [comment]
My personal belief is that secrets should not be stored in chart config files, but rather should be managed separately. However, if you (and others) prefer to mix config data with secrets, that is your choice. We can proceed with the PR but you will need to finish the contribution guideline requirements. Specifically:
- Review and agree to the contribution guidelines
- Add the documentation for the new config parameters to `chart/elastalert2/README.md`
- Update the CHANGELOG.md with this change, following the existing patterns used in that file.

**Comment by lusson-luo** [comment]
ok, let me continue with the following

**Comment by lusson-luo** [comment]
ok, i have done the above

**Review by jertel — APPROVED** [review]
Note that I changed the principal key name to smtp_auth.username, for consistency with other fields. Thanks for your contribution.

**Review by jertel — APPROVED** [review]

**Pull request merged**
