### PR TITLE
Feature/add jira url to slack

### PR DESCRIPTION
**Pull request by Hugefarsen**
## Description

Add possibility to attach an url to created Jira ticket, in the Slack alert.

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ ] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

## Questions or Comments

I have not included tests because I am not sure on how to do integration tests in python.

### CODE REVIEW

**Comment by nsano-rururu** [comment]
I'm changing the test code file even though I haven't added the test code, what do I want to do? .. Please put it back.

**Comment by nsano-rururu** [comment]
Why didn't I add the following settings to schema.yaml?
https://github.com/jertel/elastalert2/blob/master/elastalert/schema.yaml#L587
```yaml
slack_jira_url: {type: boolean}
```

**Comment by nsano-rururu** [comment]
Please correct the change log.
 
current
 ```
 [Slack] Added new option to include url to jira ticket if it is created in the same pipeline. @hugefarsen
```

fix
```
 [Slack] Added new option to include url to jira ticket if it is created in the same pipeline. - [#547](https://github.com/jertel/elastalert2/pull/547) - @hugefarsen
  ```

**Comment by jertel** [comment]
@nsano-rururu thanks for you review and noting the missing schema.

@Hugefarsen I refactored your PR. It did not match the existing Kibana URL template, and there doesn't appear to be a good reason for attaching the Jira ticket URL as a field rather than a separate attachment. If I'm wrong, let me know. Please test this change manually against your Jira and Slack to confirm it's showing up correctly in Slack. When you've confirmed it's working as expected let us know so we can merge it.

**Comment by nsano-rururu** [comment]
@jertel 

I forgot to update ruletypes.rst

**Comment by Hugefarsen** [comment]
Thank you @nsano-rururu for the review! 

Thank you very much @jertel for the update! I will test this and get back to you! 🙇

**Comment by Hugefarsen** [comment]
Yes, I have tested it now and I am satisfied with the result! :)

**Review by jertel — APPROVED** [review]

**Pull request merged**
