### PR TITLE
Removed settings related to kibana dashboard

### PR DESCRIPTION
**Pull request by nsano-rururu**
## Description

https://github.com/jertel/elastalert2/discussions/442

**delete setting**

- generate_kibana_link
- kibana_url
- use_kibana_dashboard
- use_kibana4_dashboard
- kibana4_start_timedelta
- kibana4_end_timedelta
- download_dashboard

**delete command**

- elastalert-rule-from-kibana

To check the operation locally, only the test rule execution and rule execution operations were performed.

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ ] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by nsano-rururu** [comment]
I don't know why the test is failing.

**Comment by JeffAshton** [comment]
I personally prefer links to the Discover app, but links to the Dashboard app still have their place.  If the query was passed similar to what I did for the Discover app, this could be a lot better.  Are you looking to replace this or just remove it entirely?

**Comment by nsano-rururu** [comment]
> I personally prefer links to the Discover app, but links to the Dashboard app still have their place. If the query was passed similar to what I did for the Discover app, this could be a lot better. Are you looking to replace this or just remove it entirely?

Exchange for Discover app? .. This pull request will be closed if you can respond.

**Comment by nsano-rururu** [comment]
@JeffAshton 

Please make a pull request.

**Comment by nsano-rururu** [comment]
@JeffAshton

Please post in the discussion.
https://github.com/jertel/elastalert2/discussions

**Comment by JeffAshton** [comment]
> @JeffAshton
> 
> Please post in the discussion below what to do about the dashboard.
> https://github.com/jertel/elastalert2/discussions/442

Reading that thread I'm exactly sure what you're trying to solve.  My previous comment was more in regards to how I would support dashboards in general.  Instead of creating a dashboard with a matching underlying query, as the previous solution expects, I would just pass the filter as I did with the Discover links.  Kibana uses `rison` to encode it's query string parameters. Most of the parameters will remain the same as the Discover link.  Given how I format the URL,

https://github.com/jertel/elastalert2/blob/0dbeaa19086baa8d62e137956a84500b3e7013ea/elastalert/kibana_discover.py#L82

And the format of dashboard links,

```
/_plugin/kibana/app/dashboards#/view/5e4120e0-7606-11eb-8f5a-d127bbf07cbc?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now%2Fw,to:now%2Fw))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(darkTheme:!f,hidePanelTitles:!f,useMargins:!t),query:(language:lucene,query:''),timeRestore:!t,title:'CI%20Test%20Failures%20%2F%20Most%20Failing%20Tests',viewMode:view)
```

It might just already work if you used

```
/_plugin/kibana/app/dashboards#/view/5e4120e0-7606-11eb-8f5a-d127bbf07cbc
```

As your discover app url.

**Comment by nsano-rururu** [comment]
I have no plans to address the dashboard issue anymore.

**Comment by nsano-rururu** [comment]
I thought it would be okay to wait a little for the reaction from the users, so the response priority was lowered considerably.

**Pull request closed without merging**
