### PR TITLE
add support for jira authentication via Personal Access Token

### PR DESCRIPTION
**Pull request by buzzdeee**
## Description

For Jira instances, that have basic-auth disabled, a Personal Access Token can be used.
This change allows to make use of such PAT.

## Checklist

- [X] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [X] I have manually tested all relevant modes of the change in this PR.
- [X] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

## Questions or Comments

The reading of the jira_account.yaml file seems to be shared with the smtp alerter, but the change shouldn't affect it. I'm not good with writing python tests, therefore no tests added.

### CODE REVIEW

**Comment by jertel** [comment]
Thanks for your contribution. The existing unit tests are failing due to these changes so I cannot merge this PR as-is.

**Comment by nsano-rururu** [comment]
I need to change the test code

**Comment by buzzdeee** [comment]
@jertel  @nsano-rururu 

thanks for chiming in. Unfortunately, my knowledge about python mock tests is next to zero. I don't even know if my change broke existing functionality, or only the tests would need to be adapted.
Looking at the test output, I see where it's failing, and that's where I did the change in alerts.py, but as I don't really know how these tests work, I've unfortunately no clue how to address that (best).
@nsano-rururu if you know how to address the test, would be awesome if you could do so.

thanks,
Sebastian

**Comment by nsano-rururu** [comment]
I think it's an impossible fix.
Fix alerts.py.
Because it inherits the class of alerts.py
I think it should be an implementation that defines get_account in jira.py and overrides it. Broken email.py implementation using get_account. It's terrible. this is.
Do you have no knowledge of python? Maybe.
Or rather, you don't have any programming knowledge? .. If you don't have the knowledge, you can't help noticing it, but if you're doing it at work, it's impossible, so please study.

**Comment by nsano-rururu** [comment]
I'm worried that I'm getting an error even though I haven't changed the jira test.
If you specify only user and password and do not specify api_key, it is assumed that no error will occur.
Does that mean that the implementation is not good?

**Comment by nsano-rururu** [comment]
Do not allow the merge.

**Comment by nsano-rururu** [comment]
@buzzdeee 

I think that it is not the problem that the test of api_key is not added, but the problem that the test without api_key is failed.
If the implementation is correct, the test should not fail.
If the implementation is correct, it should have just pointed out that you should add the test by specifying only api_key.

**Comment by nsano-rururu** [comment]
Isn't it necessary to enclose the username and password conditions in ()? ..

**Comment by buzzdeee** [comment]
Hi @ferozsalam 

thanks for the explanations of my logic error. I only could test the api_key version, as that's the type of Jira server I've around, and that case just worked for me.

Also thanks for the suggestion regarding overriding get_account in jira.py, I'll look into that.

**Comment by ferozsalam** [comment]
Nicely done on getting the tests to work :+1: 

Are you able to add a unit test to check that if an API key alone is defined, things work as expected? This would be very similar to the existing Jira tests.

**Comment by buzzdeee** [comment]
Hi,

updated version now with tests passing:

- reverted changes to alerts.py
- override get_account in alerters/jira.py
- changed the logic in the if statement a bit, all these NOTs cobined with AND and OR were too confusing to me, that's why I didn't catched it initially. At least for me, this is now much more easy to follow.
- had to update the tests, a bit of google foo and reading pointed out, mock patch has to patch where function is used, not where it's declared.

Additionally, I tested with a config file:
 * only with user given -> exception
 * only with password given -> exception
 * with user/password -> works
 * with apikey -> works

As I understand my code, the apikey takes precedence. So if apikey is combined with user or password or both in the authentication file, it will try to use the apikey, without falling back to user/password in case that doesn't work. hope that's fine/fair enough ;)

**Comment by buzzdeee** [comment]
@ferozsalam 

now there should be a test at the end of jira_test.py.
I hope I got it all right, at least it's passing now after a few attempts ;)

**Review by nsano-rururu — DISMISSED** [review]

**Review by jertel — APPROVED** [review]

**Pull request merged**
