### PR TITLE
Migrate remaining alerters out of alerts.py

### PR DESCRIPTION
**Pull request by ferozsalam**
Migrate all the remaining alerters!

Will do `alerts_test.py` in a following commit, probably over the weekend.

### CODE REVIEW

**Review by jertel — APPROVED** [review]

**Comment by nsano-rururu** [comment]
@ferozsalam 

What is the merit of not unifying the writing style in "from .alerters.xxx import xxx Alerter"? .. That's what the test code does. Mystery is.

the current

```
import elastalert.alerters.alerta
import elastalert.alerters.chatwork
import elastalert.alerters.command
import elastalert.alerters.datadog
import elastalert.alerters.debug
import elastalert.alerters.discord
import elastalert.alerters.gitter
import elastalert.alerters.googlechat
import elastalert.alerters.httppost
import elastalert.alerters.line
import elastalert.alerters.pagertree
import elastalert.alerters.exotel
import elastalert.alerters.servicenow
import elastalert.alerters.ses
import elastalert.alerters.stomp
import elastalert.alerters.telegram
import elastalert.alerters.twilio
import elastalert.alerters.victorops
import elastalert.alerters.elastalert.dingtalk
import elastalert.alerters.elastalert.thehive
```

```
    # Used to map names of alerts to their classes
    alerts_mapping = {
        'email': EmailAlerter,
        'jira': JiraAlerter,
        'opsgenie': OpsGenieAlerter,
        'stomp': elastalert.alerters.stomp.StompAlerter,
        'debug': elastalert.alerters.debug.DebugAlerter,
        'command': elastalert.alerters.command.CommandAlerter,
        'sns': SnsAlerter,
        'ms_teams': MsTeamsAlerter,
        'slack': SlackAlerter,
        'mattermost': MattermostAlerter,
        'pagerduty': PagerDutyAlerter,
        'exotel': elastalert.alerters.exotel.ExotelAlerter,
        'twilio': elastalert.alerters.twilio.TwilioAlerter,
        'victorops': elastalert.alerters.victorops.VictorOpsAlerter,
        'telegram': elastalert.alerters.telegram.TelegramAlerter,
        'googlechat': elastalert.alerters.googlechat.GoogleChatAlerter,
        'gitter': elastalert.alerters.gitter.GitterAlerter,
        'servicenow': elastalert.alerters.servicenow.ServiceNowAlerter,
        'alerta': elastalert.alerters.alerta.AlertaAlerter,
        'post': elastalert.alerters.httppost.HTTPPostAlerter,
        'pagertree': elastalert.alerters.pagertree.PagerTreeAlerter,
        'linenotify': elastalert.alerters.line.LineNotifyAlerter,
        'hivealerter': elastalert.alerters.thehive.HiveAlerter,
        'zabbix': ZabbixAlerter,
        'discord': elastalert.alerters.discord.DiscordAlerter,
        'dingtalk': elastalert.alerters.dingtalk.DingTalkAlerter,
        'chatwork': elastalert.alerters.chatwork.ChatworkAlerter,
        'datadog': elastalert.alerters.datadog.DatadogAlerter,
        'ses': elastalert.alerters.ses.SesAlerter
    }
```

after


```
from .alerters.alerta import AlertaAlerter
from .alerters.chatwork import ChatworkAlerter
from .alerters.command import CommandAlerter
from .alerters.datadog import DatadogAlerter
from .alerters.debug import DebugAlerter
from .alerters.discord import DiscordAlerter
from .alerters.gitter import GitterAlerter
from .alerters.googlechat import GoogleChatAlerter
from .alerters.httppost import HTTPPostAlerter
from .alerters.line import LineNotifyAlerter
from .alerters.pagertree import PagerTreeAlerter
from .alerters.exotel import ExotelAlerter
from .alerters.servicenow import ServiceNowAlerter
from .alerters.ses import SesAlerter
from .alerters.stomp import StompAlerter
from .alerters.telegram import TelegramAlerter
from .alerters.twilio import TwilioAlerter
from .alerters.victorops import VictorOpsAlerter
from .alerters.dingtalk import DingTalkAlerter
from .alerters.thehive import HiveAlerter
```

```
    # Used to map names of alerts to their classes
    alerts_mapping = {
        'email': EmailAlerter,
        'jira': JiraAlerter,
        'opsgenie': OpsGenieAlerter,
        'stomp': StompAlerter,
        'debug': DebugAlerter,
        'command': CommandAlerter,
        'sns': SnsAlerter,
        'ms_teams': MsTeamsAlerter,
        'slack': SlackAlerter,
        'mattermost': MattermostAlerter,
        'pagerduty': PagerDutyAlerter,
        'exotel': ExotelAlerter,
        'twilio': TwilioAlerter,
        'victorops': VictorOpsAlerter,
        'telegram': TelegramAlerter,
        'googlechat': GoogleChatAlerter,
        'gitter': GitterAlerter,
        'servicenow': ServiceNowAlerter,
        'alerta': AlertaAlerter,
        'post': HTTPPostAlerter,
        'pagertree': PagerTreeAlerter,
        'linenotify': LineNotifyAlerter,
        'hivealerter': HiveAlerter,
        'zabbix': ZabbixAlerter,
        'discord': DiscordAlerter,
        'dingtalk': DingTalkAlerter,
        'chatwork': ChatworkAlerter,
        'datadog': DatadogAlerter,
        'ses': SesAlerter
    }
```

**Comment by ferozsalam** [comment]
Hey @nsano-rururu - Good question. For the first few alerters, I did the migration manually, and did the imports in the original style.

I then discovered that PyCharm has functionality to automate the refactoring of classes into separate files, which allowed me to move all the remaining functions quickly at one time. However, PyCharm uses the `import elastalert.alerters.xyz` syntax when doing the automatic import.

I agree that it would be neater to import the class file directly, but I think I would prefer to convert the entire file to use absolute imports over relative imports, just because most Python style guides seem to recommend absolute imports ([PEP-8](https://www.python.org/dev/peps/pep-0008/#imports), [Google style guide](https://www.python.org/dev/peps/pep-0008/#imports)).

I propose using the following structure:

```
from elastalert.alerters.alerta import AlertaAlerter
...
```

and then:

```
alerts_mapping = {
        'alerta': AlertaAlerter,
...
```

and I agree, making it consistent would be a lot better - I can do this in another diff soon.

**Comment by nsano-rururu** [comment]
@ferozsalam

Thank you for your answer.
I learned a lot about python.
 I think it would be nice to change all relative imports to absolute imports, but is it possible to make relative imports an error in linter when running a test?

**Comment by ferozsalam** [comment]
> I think it would be nice to change all relative imports to absolute imports, but is it possible to make relative imports an error in linter when running a test?

@nsano-rururu I agree about changing all the imports - it looks like flake8 can do this with the help of [a plugin,](https://pypi.org/project/flake8-tidy-imports/) perhaps something to add for the future.

**Pull request merged**
