### PR TITLE
Lark alerter support

### PR DESCRIPTION
**Pull request by seanyinx**
## Description

- Added [Lark](https://www.larksuite.com/en_us/) alerter

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Please add documentation about Lark alerter
https://github.com/jertel/elastalert2/blob/master/docs/source/ruletypes.rst

**Comment by nsano-rururu** [comment]
I don't think there is a need to modify /Dockerfile-test for this pull request.

**Comment by nsano-rururu** [comment]
It seems that the description in schema.yaml is incorrect.
Please modify as below.
```yaml
  ### Lark
  lark_bot_id: {type: string}
  lark_msgtype: {type: string, enum: ['text']}
```

**Comment by jertel** [comment]
@seanyinx Do you think you'll have time to update the docs and make those minor changes @nsano-rururu suggested in the next few days? If so I'll be able to include this in the next release. It's not urgent so if you need more time we can leave this for the next in about 2 months. Thanks!

**Comment by seanyinx** [comment]
> @seanyinx Do you think you'll have time to update the docs and make those minor changes @nsano-rururu suggested in the next few days? If so I'll be able to include this in the next release. It's not urgent so if you need more time we can leave this for the next in about 2 months. Thanks!

Sorry, I was on vacation last week. It's not urgent and I will make the changes as suggested today.

**Comment by seanyinx** [comment]
> It seems that the description in schema.yaml is incorrect. Please modify as below.
> 
> ```yaml
>   ### Lark
>   lark_bot_id: {type: string}
>   lark_msgtype: {type: string, enum: ['text']}
> ```

@nsano-rururu @jertel Docs on Lark alerter added and suggested changes made. Thanks.

**Review by jertel — APPROVED** [review]

**Pull request merged**
