### PR TITLE
add_alertmanager_resolve_timeout

### PR DESCRIPTION
**Pull request by eveningcafe**
## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by eveningcafe** [comment]
The thing is, alertmanager has a default resov_timeout is 5 minutes, meaning after 5 minutes if it doesn't r receive any repeat alert it will consider the alert stop firing. Sure, you can set "realert" below 5 min in your rules to keep alert fire, but it will affect another alert output. I think the best option is we can keep that timeout configurable in the rules, like this :\

```
alertmanager_alertname: "freq_alert" 
alertmanager_resolve_timeout: 5 # it will affect end_time - aka time to live - of each alert sent to alertmanager.
```

Users who config the rules can be aware of this config and expect the right behavior for alertmanager.

**Comment by eveningcafe** [comment]
@jertel

**Comment by nsano-rururu** [comment]
Please add alertmanager_resolve_timeout to the documentation. stomach. If there is a default value, please also provide the default value.
https://github.com/jertel/elastalert2/blob/master/docs/source/ruletypes.rst#alertmanager

Please use the validation check setting of alertmanager_resolve_timeout
https://github.com/jertel/elastalert2/blob/master/elastalert/schema.yaml#L321
```yaml
alertmanager_resolve_timeout: {type: integer}
```

**Comment by nsano-rururu** [comment]
Please add test code for alertmanager_resolve_timeout
https://github.com/jertel/elastalert2/blob/master/tests/alerters/alertmanager_test.py

**Comment by nsano-rururu** [comment]
Please update CHANGELOG.md

**Comment by eveningcafe** [comment]
ok I'll do it now. ~ chotto matte. But the ideal ok right?

**Comment by jertel** [comment]
Hello @eveningcafe: Are you planning to continue this PR? If so I'll leave it open for a couple more weeks. Let us know.

Thanks!

**Comment by eveningcafe** [comment]
oh yes, sorry. I'll do. please leave it open

**Comment by nsano-rururu** [comment]
@eveningcafe 

Are there minimum and maximum values for alertmanager_resolve_timeout settings?

**Comment by eveningcafe** [comment]
Hey guys, how does mock build respose of my request to 'http://alertmanager:9093' ? Here
image
Sorry, I'm new to mock and  currently failing some unit tests. :(
image

**Review by jertel — APPROVED** [review]
I refactored your implementation to make it a non-breaking change, and to utilize a consistent time configuration, similar to timeframe and buffer_time. Also added a unit test.

**Pull request merged**
