### PR TITLE
VictorOps: Set `state_message` and `entity_display_name` from rule

### PR DESCRIPTION
**Pull request by ChristophShyper**
This change adds all data gathered from ElasticSearch to VictorOps's payload, which then can be used easily with transmogrifier.

If `victorops_entity_display_name` is not set then `entity_display_name` is taking value of `alert_subject`. Or randomized by VictorOps.

### CODE REVIEW

**Comment by nsano-rururu** [comment]
It has changed its original behavior and will not be merged unless you modify the test code.

**Comment by ChristophShyper** [comment]
I noticed that. Maybe I'll have a look some other day to correct it.

**Comment by ChristophShyper** [comment]
@nsano-rururu Can you re-run the tests?
I tried to execute them locally with `make test` and `make test-docker` but all are passing properly.
```
642 passed, 4 skipped in 46.04s
```

**Comment by ChristophShyper** [comment]
Hi @nsano-rururu  I've updated the tests for the new payload content.

**Comment by nsano-rururu** [comment]
Isn't it necessary to modify the document?
https://github.com/jertel/elastalert2/blob/master/docs/source/ruletypes.rst#splunk-on-call-formerly-victorops

**Comment by ChristophShyper** [comment]
You're right. I've added there also information about the default behaviour.

**Comment by nsano-rururu** [comment]
I think I need to add some test code if victorops_entity_display_name is not set

**Comment by ChristophShyper** [comment]
Added it as well now. Sorry, it's 2 AM and I'm working for 18 hours already so my mind is shutting down...

**Review by nsano-rururu — COMMENTED** [review]
Please add your changes to 2.x.x New features in change logs.
https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md

**Comment by ChristophShyper** [comment]
Done. Added as breaking changes, since the subject could change.

**Review by nsano-rururu — APPROVED** [review]

**Comment by nsano-rururu** [comment]
@jertel 

The review is over. Is there anything else I can point out?

**Comment by jertel** [comment]
This was added to the _Breaking Changes_ section of the changelog. But is this really a breaking change? For users that have VictorOps in use today, how will upgrading to the next version break their alerts?

**Comment by ChristophShyper** [comment]
Depending on transmogrifier configuration, if it reads alert subject might not trigger notification if the subject was changed.

**Review by jertel — APPROVED** [review]
Thanks for the quick response, and for the PR contribution. Hoping you get some time off soon! :)

**Pull request merged**
