### PR TITLE
Fix ca certs schema

### PR DESCRIPTION
**Pull request by Goggin**
## Description

*_ca_certs options should allow string as well so that a cert bundle can be specified

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ ] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by jertel — APPROVED** [review]
Thanks for making this change to all the affected alerters!

**Comment by Goggin** [comment]
> Thanks for making this change to all the affected alerters!

No problem, ran into it with http and figured check all of them in case

**Comment by nsano-rururu** [comment]
@jertel 
Did you really think it was okay to merge? It will affect your operation.
https://github.com/jertel/elastalert2/blob/master/elastalert/alerters/alertmanager.py#L66
verify = self.ca_certs

https://github.com/jertel/elastalert2/blob/master/elastalert/alerters/alertmanager.py#L76
verify=verify,

**Comment by nsano-rururu** [comment]
I deleted the comment because it was a mistake.

**Pull request merged**
