### PR TITLE
Adding Image Pull Secret to Helm Chart

### PR DESCRIPTION
**Pull request by robrankin**
## Description

Adding Image Pull Secret to the chart, so we can use private repositories.

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ ] I have included unit tests for my changes or additions.
- [ ] I have successfully run `make test-docker` with my changes.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by lepouletsuisse** [comment]
I think this PR is linked to [this discussion](https://github.com/jertel/elastalert2/discussions/245).
However, I think it is still a good idea to be able to set the imagePullSecrets on the deployment itself

**Comment by jertel** [comment]
I agree. Will merge once the changelog is updated. I'll update it myself if no one else gets to it this week.

**Comment by robrankin** [comment]
Updated the changelog.  Anything else needed?

**Comment by jertel** [comment]
Thank you! Also check that other thread @lepouletsuisse mentioned in case it might be simpler if your deployments all use the same private image repo.

**Review by jertel — APPROVED** [review]

**Pull request merged**
