### PR TITLE
Fix missing colon on schema.yml and add unit test on it

### PR DESCRIPTION
**Pull request by Isekai-Seikatsu**
## Description

I think there are some missing colons.

I found this when I using code generator tool, not sure if there is a unit test on schema.yml.
## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [ ] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Please add ChangeLog.
https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md#other-changes

**Comment by nsano-rururu** [comment]
Certainly there is no unit test for schema.yml

**Comment by nsano-rururu** [comment]
No Checklist has been checked. Didn't you see the guidelines?

**Review by jertel — DISMISSED** [review]

**Comment by Isekai-Seikatsu** [comment]
I add a unit test to `load_rule_schema`, hope this is helpful.

**Review by jertel — APPROVED** [review]

**Pull request merged**
