### PR TITLE
Fix #310 / #307

### PR DESCRIPTION
**Pull request by mrfroggg**

### CODE REVIEW

**Comment by mrfroggg** [comment]
Dict merge will overwrite duplicate keys with last element:

```
a = {'a': 1, 'b': 2, 'c': 3}
b = {'c': 33, 'd': 44}
{**a, **b}
Out[4]: {'a': 1, 'b': 2, 'c': 33, 'd': 44}
```

**Comment by ferozsalam** [comment]
As we have Python 3.9 in the project, it might be neater to write this like:

`template_values = self.match | self.rule`

And then use the `template_values` where required.

**Comment by mrfroggg** [comment]
> As we have Python 3.9 in the project, it might be neater to write this like:
> 
> `template_values = self.match | self.rule`
> 
> And then use the `template_values` where required.

Oh, I never used `|` before, I'll update my PR!

**Comment by mrfroggg** [comment]
Updated the PR and added test for alert_text_jinja

**Review by jertel — APPROVED** [review]
Nice work, thank you!

**Pull request merged**
