### PR TITLE
upgrade to Python 3.12

### PR DESCRIPTION
**Pull request by jertel**
## Description

Upgrade to Python 3.12 and correct unit tests that broke. 

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by jertel** [comment]
Still pending: replacement of utcnow(). This isn't critical but would be nice to finish it now versus waiting.

**Comment by jertel** [comment]
Update: I've resolved the majority of the deprecation notices. There are still a few remaining:

python_dateutil - this package appears to have been abandoned. There hasn't been an update in years. I've removed some references to it but there are about 4 remaining that will need to be refactored away from `dateutil`.

botocore - there is an open issue tracking this deprecation: https://github.com/boto/boto3/issues/3889

tencentcloud - I don't see any signs that the team maintaining that project is aware of the deprecation. In fact it looks like they are only certified with Python 3.10. This is the line causing the deprecation: https://github.com/TencentCloud/tencentcloud-sdk-python/blob/4c3ac77e720958029de11d3cd0f55da5fdcbf5b8/tencentcloud/common/abstract_client.py#L209

I think this PR is sufficient for the next release. A separate effort can resume the deprecation resolutions later.

**Review by nsano-rururu — APPROVED** [review]

**Comment by nsano-rururu** [comment]
@jertel 

> python_dateutil - this package appears to have been abandoned. There hasn't been an update in years. I've removed some references to it but there are about 4 remaining that will need to be refactored away from dateutil.

It seems that dateutil has been updated. It seems that there was also a response to the deprecation warning of python3.12.

https://github.com/dateutil/dateutil/releases

**Comment by jertel** [comment]
Thanks. Updated in #1388.

**Pull request merged**
