### PR TITLE
upgrade to Python 3.13

### PR DESCRIPTION
**Pull request by nsano-rururu**
## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ ] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [ ] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by jertel — APPROVED** [review]

**Comment by jertel** [comment]
ReadTheDocs failed to build the doc set. I put that file only back to 3.12.

image

**Comment by Karql** [comment]
You should add breaking change to release https://github.com/jertel/elastalert2/releases/tag/2.21.0  because you dropped version 3.12.

btw. IMO this drop was done too fast. You should consider alpine linux releases because this is very popular system.

**Comment by jertel** [comment]
@Karql Thanks for bringing this up. I agree, the removal of 3.12 support should have been mentioned as a breaking change. It was properly marked as a breaking change in the previous release when 3.9-3.11 was dropped.

@nsano-rururu Was there a specific reason you removed support for 3.12? If not we can add that support back for a few more months.

**Comment by nsano-rururu** [comment]
@jertel 

There's no particular reason.
You don't need to ask my consent for how to proceed from now on.
I haven't used elastalert2 for quite some time now.

**Comment by nsano-rururu** [comment]
@jertel 

The [elastalert2-server](https://github.com/Karql/elastalert2-server) maintained by Karql uses a node docker image. Because it is based on alpine, it will take some time to get the latest python support.

**Comment by nsano-rururu** [comment]
@Karql 

The background should be explained properly. It is an unofficial tool. elastalert2-server is

**Comment by Karql** [comment]
There are many use cases for this tool.
For example, someone might run it directly on their system. There are systems that are more security-focused, where new application versions are added to the repository more slowly.

I see no reason to drop support for older Python versions.
None of the dependencies in use require this.
I also don’t see any specific features being used that are only available in newer Python versions.

Additionally, it's worth mentioning that version 3.12 will be supported for another 4 years.

image

Like I've said - In my opinion, dropping support for older versions just two days after the release of a new one is definitely too fast.

**Pull request merged**
