### PR TITLE
Add impact and urgency as optional params for the servicenow alerter

### PR DESCRIPTION
**Pull request by randolph-esnet**
Extend the Servicenow alerter to support two new parameters: impact and urgency. 

More info on these parameters can be found on the [Servicenow doc page on defining priority lookup rules](https://docs.servicenow.com/bundle/quebec-it-service-management/page/product/incident-management/task/def-prio-lookup-rules.html).

These are added as optional parameters to ensure backwards compatibility.

### CODE REVIEW

**Comment by nsano-rururu** [comment]
It's an additional `impact` and `urgency`, but I think it's better to prefix it with `servicenow_`.

**Comment by nsano-rururu** [comment]
Although it is an additional impact and urgency, since integer is specified in schema.yaml, in the actual rule, if you enclose it in single quotation marks or double quotation marks, an error will occur when executing the actual rule.
It doesn't cause an error in unit tests, but in the sense that it is close to the actual data, I think it is better not to enclose it in single quotes.

**Comment by randolph-esnet** [comment]
> It's an additional `impact` and `urgency`, but I think it's better to prefix it with `servicenow_`.

Thank you. I'll add the servicenow prefix for the new parameters.

**Comment by randolph-esnet** [comment]
> It's an additional `impact` and `urgency`, but I think it's better to prefix it with `servicenow_`.

Thank you. I'll add the servicenow prefix.

**Comment by randolph-esnet** [comment]
> ...I think it is beter not to enclose it in single quotes.

To make sure I understand, are you suggesting to omit the quotes in the unit test?

**Comment by nsano-rururu** [comment]
If schema.yaml is written as follows, the value will be checked and an error will occur when a rule other than 1,2,3 is specified and the rule is executed.

```
  servicenow_impact: {type: integer, minimum: 1, maximum: 3}
  servicenow_urgency: {type: integer, minimum: 1, maximum: 3}
```

**Comment by nsano-rururu** [comment]
> > ...I think it is beter not to enclose it in single quotes.
> 
> To make sure I understand, are you suggesting to omit the quotes in the unit test?

If you don't agree, you can leave it as it is.

**Comment by randolph-esnet** [comment]
> If schema.yaml is written as follows, the value will be checked and an error will occur when a rule other than 1,2,3 is specified and the rule is executed.
> 
> ```
>   servicenow_impact: {type: integer, minimum: 1, maximum: 3}
>   servicenow_urgency: {type: integer, minimum: 1, maximum: 3}
> ```
> 
> Supplement. jsonschema checks the key and data type etc. listed in schema.yaml.

Great suggestion. Thank you.

**Review by jertel — APPROVED** [review]
Thanks!!

**Pull request merged**
