### PR TITLE
Migrate all the alerter tests into individual files

### PR DESCRIPTION
**Pull request by ferozsalam**

### CODE REVIEW

**Comment by nsano-rururu** [comment]
@ferozsalam

Why didn't you move the following files to the alerters folder?

thehive.py
dingtalk.py

**Comment by ferozsalam** [comment]
> @ferozsalam
> 
> Why didn't you move the following files to the alerters folder?
> 
> thehive.py
> dingtalk.py

I didn't see them, thanks for letting me know.

I will move them in a separate PR.

**Review by jertel — APPROVED** [review]

**Comment by nsano-rururu** [comment]
@ferozsalam 

Only the file name of zabbix test code ends with ``_text.py`` instead of  ``_test.py``.

**the current**

zabbix_text.py

**Correct name**

zabbix_test.py

**Comment by ferozsalam** [comment]
@nsano-rururu thanks, will fix.

**Pull request merged**
