### PR TITLE
feat: Add duedate

### PR DESCRIPTION
**Pull request by fionera**
## Description
Add Support for DueDate

## Checklist

- [ ] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ ] I have included unit tests for my changes or additions.
- [ ] I have successfully run `make test-docker` with my changes.
- [ ] I have manually tested all relevant modes of the change in this PR.
- [ ] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [ ] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

## Questions or Comments
I also set the type of the account field (this comes from the "Tempo" extension)

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Is the change affecting all users using jira for alerts?

**Comment by nsano-rururu** [comment]
There is no addition to changelog.

**Comment by nsano-rururu** [comment]
There are no checks in the Checklist. Does that mean you haven't even checked the operation locally or in the guide?

**Comment by nsano-rururu** [comment]
Is it unnecessary to update the document?

**Comment by nsano-rururu** [comment]
Won't you add test code?

**Comment by nsano-rururu** [comment]
Did you run make test-docker to see if other tests aren't working?

**Comment by fionera** [comment]
Ok no sorry that where way too many mails. I sadly dont have the Time/Knowledge for this and just wanted to maybe share the feature

**Pull request closed without merging**
