### PR TITLE
[Feature] support prometheus-operator serviceMonitor and prometeusRules

### PR DESCRIPTION
**Pull request by PedroMSantosD**
## Description

This enables exposing elastalert2 using the 'metrics' configuration section of the Chart. It also supports creating both serviceMonitor and prometheusRules custom resources for prometheus-operator to be able to automacitally detect and reconfigure prometheus accordingly.

Breaking change: 
* The labelset of kubernetes objects have been changed to match helm_charts recommended labels. You'll need to uninstall and reinstall the chart for it to work.
* Enabling of the metrics endpoint, configuration of pod port and annotations have been moved to metrics section.

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

## Questions or Comments

no manual tests included for the chart. It has been deployed through helm_install without issues.

### CODE REVIEW

**Review by jertel — CHANGES_REQUESTED** [review]
Thanks for submitting this. Please take a look at the README.md descriptions -- I spotted several typos on the new field descriptions. I'll leave it open for a few days to let others comment, since, as you said, it will impact existing chart users.

**Comment by PedroMSantosD** [comment]
Hi, file updated. I have a question thought,
most of the files have been adapted from repo: https://github.com/bitnami/charts/tree/master/bitnami/thanos/templates
Does this have to be mentioned anywhere ?

**Comment by jertel** [comment]
Please correct the checklist in this PR. There are slashes instead of x's and it makes it difficult to understand which checklist items you are marking as completed. Use an `x` to mark a check list item as complete. If it does not apply, such as unit test updates, leave it blank.

**Review by jertel — APPROVED** [review]

**Comment by albertoCrego** [comment]
@jertel when will be available the new release? This feature's really useful.

**Comment by jertel** [comment]
The current plan is this weekend.

**Pull request merged**
