### PR TITLE
Patch position of initContainers keyword

### PR DESCRIPTION
**Pull request by aturpin1789**
## Description

Patch to #1140 
The `initContainers` keyword in templates/deployments.yaml was inside the range of the `containers` keyword causing error for deployment due to the lack of container options interpretation

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [ ] I have included unit tests for my changes or additions.
- [ ] I have successfully run `make test-docker` with my changes.
- [ ] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by georgestack — APPROVED** [review]

**Review by georgestack — APPROVED** [review]

**Review by georgestack — APPROVED** [review]

**Comment by jertel** [comment]
In the interest of preventing this in the future, can you help me understand how this was missed in your testing on the previous PR? Part of the checklist for submitting PRs requires submitters to confirm they have tested their change and verified it works. Your PR had that checkbox checked.

**Comment by aturpin1789** [comment]
I'm very sorry because I didn't test my modifications.
I know how to test Python code but I have any idea how to test helm chart configurations and I didn't find already written tests in templates section to run and to complete.
I would have asked how to test helm chart configurations instead of dumb checking.

**Comment by aturpin1789** [comment]
I'm very sorry because I didn't test my modifications.
I know how to test Python code but I have any idea how to test helm chart configurations and I didn't find already written tests in templates section to run and to complete.
I would have asked how to test helm chart configurations instead of dumb checking.

**Comment by jertel** [comment]
There are no unit tests for helm charts. The checkbox I'm referring to states "I have manually tested ... the change in this PR". What I need to know is are you actually testing that you're able to deploy this chart to a kubernetes cluster before you submit the PR?

**Review by jertel — APPROVED** [review]
Approving based on @georgestack comment.

**Comment by aturpin1789** [comment]
Hello @jertel

Could you apply those changes in Artifact Hub ?

Thanks

**Comment by jertel** [comment]
Hello. Artifact Hub will be updated when a new version of ElastAlert 2 is released. Releases are typically 1-2 months apart. The corrected helm chart will be available with the next version.

**Pull request merged**
