### PR TITLE
Change Zabbix alerter

### PR DESCRIPTION
**Pull request by timeforplanb123**
## Description

Add the ability to specify `zbx_host` from available elasticsearch field.

By default, zabbix alerter send "1" to single host with specified `zbx_host` hostname. For a large number of hosts in zabbix, it would be convenient to specify `zbx_host` value from available elasticsearch field.

More details - #812 

## Checklist

- [x] I have reviewed the [contributing guidelines](https://github.com/jertel/elastalert2/blob/master/CONTRIBUTING.md).
- [x] I have included unit tests for my changes or additions.
- [x] I have successfully run `make test-docker` with my changes.
- [x] I have manually tested all relevant modes of the change in this PR.
- [x] I have updated the [documentation](https://elastalert2.readthedocs.io).
- [x] I have updated the [changelog](https://github.com/jertel/elastalert2/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by nsano-rururu** [comment]
Add the following verification check settings.
https://github.com/jertel/elastalert2/blob/master/elastalert/schema.yaml#L688
```yaml
zbx_host_from_field: {type: boolean}
```

**Comment by timeforplanb123** [comment]
Added

**Comment by jertel** [comment]
@nsano-rururu are you ok with the style changes being made with this commit? We usually ask that contributors adopt the existing style already used within the source code, to avoid having a mixture of varying coding styles within the project. If that's not important to you we can accept it as-is.

Ex:
image

**Comment by nsano-rururu** [comment]
If you want to modify existing code, it's best to follow your existing coding style.

**Comment by timeforplanb123** [comment]
So I need to change the `black` formatted code and return to the current style?

**Comment by jertel** [comment]
That screenshot I pasted was a small example. What we would prefer is to undo all of your formatting changes, and only submit the logic changes required for your PR functionality.

**Comment by timeforplanb123** [comment]
Fixed :)

**Review by jertel — APPROVED** [review]

**Comment by jertel** [comment]
Thanks for the contribution!

**Pull request merged**
